version: '3.8'

services:
  app:
    build:
      context: .
    volumes:
      - .:/var/www
    networks:
      - appnet

  web:
    image: nginx:alpine
    entrypoint: [ "/bin/sh", "-c", "/var/www/nginx/start.sh" ]
    ports:
      - "80:${PORT}"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - appnet

networks:
  appnet:
